services:
  server_docker:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: python_app
    ports:
      - "${PYTHON_APP_PORT}:5000"
    volumes:
      - ../.:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - network_python
    depends_on:
      - mysql
    command: python app.py

  mysql:
    image: mysql:latest
    container_name: mysql_python
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/database:/docker-entrypoint-initdb.d
      - persistent_python:/var/lib/mysql:rw
    networks:
      - network_python

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_python
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - network_python

networks:
  network_python:
    name: network_python

volumes:
  persistent_python:
